name: Start Codespace

on:
  schedule:
    - cron: '0 3 * * *'    # 9:00 AM GMT
    - cron: '30 7 * * *'   # 13:30 PM GMT
  workflow_dispatch:        # manual trigger

jobs:
  start-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Start Codespace via API
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CODESPACE_NAME: silver-space-barnacle-jjwp75v9xx77h5j9j
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/user/codespaces/$CODESPACE_NAME/start