name: Start Minecraft Server

permissions:
  contents: read
  actions: write
  
on:
  schedule:
    - cron: '30 09 * * *'   # 3:00 PM IST
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Start Codespace
        run: gh codespace start --codespace silver-space-barnacle-jjwp75v9xx77h5j9j

      - name: Start Minecraft Server
        run: gh codespace ssh --codespace silver-space-barnacle-jjwp75v9xx77h5j9j -c "./start-server.sh"